# Generated by Django 4.2.5 on 2023-09-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0002_delete_movies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('adult', models.BooleanField()),
                ('title', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('release_date', models.CharField(max_length=12)),
                ('vote_average', models.DecimalField(decimal_places=1, max_digits=3)),
                ('popularity', models.DecimalField(decimal_places=3, max_digits=7)),
            ],
            options={
                'db_table': 'Movies',
            },
        ),
    ]
