# Generated by Django 4.2.5 on 2023-09-10 03:40

import django.core.validators
from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_movies_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='popularity',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='movies',
            name='vote_average',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
