# Generated by Django 4.2.5 on 2023-09-10 04:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_movies_popularity_alter_movies_vote_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='vote_average',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
